import type { Product } from "@/features/products/types/product.types";

export const mockProducts: Product[] = [
  {
    id: "fleur-de-lune",
    name: "Fleur de Lune",
    description: "A luminous floral composition of jasmine and white musk.",
    notes: "Floral / Jasmine & White Musk",
    price: 195,
    images: ["/images/products/fleur-de-lune.png"],
    category: "pure-extractions",
    scentFamily: "floral",
    occasion: "daywear",
    options: [],
    availability: "Available in Atelier",
    volumeOptions: [
      { size: "30 ml", price: 125 },
      { size: "50 ml", price: 160 },
      { size: "100 ml", price: 195 },
    ],
    scentAnatomy: {
      story:
        "Fleur de Lune captures the ethereal grace of night-blooming jasmine illuminated by moonlight. An opening of dew-kissed petals unfolds into a powdery heart of velvety iris, resting gently on clean white musk.",
      topNotes: "Neroli Petals, Dewberry, Fresh Bergamot",
      heartNotes: "Night-Blooming Jasmine, Florentine Iris",
      baseNotes: "White Musk, Sheer Cedarwood, Cashmere Amber",
    },
  },
  {
    id: "santal-parchment",
    name: "Santal Parchment",
    description:
      "Santal Parchment wraps around the skin like vintage vellum paper. It opens with bright top notes, shifting to clean papyrus and warm, rich sandalwood that dry down into dry cardamom and amber.",
    notes: "Woody / Sandalwood & Cardamom",
    price: 220,
    images: [
      "/images/products/santal-parchment.png",
      "/images/products/santal-parchment-detail.jpg",
      "/images/products/santal-parchment-craft.jpg",
      "/images/products/santal-parchment-bottle.jpg",
    ],
    category: "pure-extractions",
    scentFamily: "woody",
    occasion: "evening",
    options: [],
    availability: "Available in Atelier",
    volumeOptions: [
      { size: "30 ml", price: 140 },
      { size: "50 ml", price: 180 },
      { size: "100 ml", price: 220 },
    ],
    scentAnatomy: {
      story:
        "Santal Parchment wraps around the skin like vintage vellum paper. It opens with bright top notes, shifting to clean papyrus and warm, rich sandalwood that dry down into dry cardamom and amber.",
      topNotes: "Sicilian Bergamot, Pink Pepper",
      heartNotes: "Egyptian Jasmine Sambac, Papyrus",
      baseNotes: "West Indian Sandalwood, Cardamom, Amber",
    },
  },
  {
    id: "noir-cocoon",
    name: "Noir Cocoon",
    description: "An oriental blend of tobacco and amber.",
    notes: "Oriental / Tobacco & Amber",
    price: 240,
    images: ["/images/products/noir-cocoon.png"],
    category: "private-reserve",
    scentFamily: "oriental",
    occasion: "evening",
    options: [],
    availability: "Available in Atelier",
    volumeOptions: [
      { size: "30 ml", price: 155 },
      { size: "50 ml", price: 195 },
      { size: "100 ml", price: 240 },
    ],
    scentAnatomy: {
      story:
        "Noir Cocoon is an intimate sanctuary of warmth and smoky opulence. Honeyed tobacco leaves gently surrender to rich bourbon vanilla and dark Baltic amber.",
      topNotes: "Spiced Honey, Bitter Orange, Coriander",
      heartNotes: "Aged Tobacco Leaf, Roasted Tonka, Cacao",
      baseNotes: "Dark Baltic Amber, Benzoin Resin, Patchouli",
    },
  },
  {
    id: "sol-dor",
    name: "Sol d'Or",
    description: "A fresh coastal blend of bergamot and sea salt.",
    notes: "Fresh / Bergamot & Sea Salt",
    price: 185,
    images: ["/images/products/sol-dor.png"],
    category: "pure-extractions",
    scentFamily: "fresh",
    occasion: "daywear",
    options: [],
    availability: "Available in Atelier",
    volumeOptions: [
      { size: "30 ml", price: 120 },
      { size: "50 ml", price: 150 },
      { size: "100 ml", price: 185 },
    ],
    scentAnatomy: {
      story:
        "Sol d'Or encapsulates radiant golden sunlight cascading over Mediterranean cliffs. Salty oceanic breezes intermingle with sun-drenched citrus and driftwood.",
      topNotes: "Calabrian Bergamot, Sea Salt, Mandarin",
      heartNotes: "Coastal Rosemary, Orange Blossom, Neroli",
      baseNotes: "Sun-Bleached Driftwood, Sheer Musk, Ambergris",
    },
  },
  {
    id: "atelier-oud",
    name: "Atelier Oud",
    description: "Rich oud deepened with saffron.",
    notes: "Woody / Rich Oud & Saffron",
    price: 310,
    images: ["/images/products/atelier-oud.png"],
    category: "atelier-oils",
    scentFamily: "woody",
    occasion: "special-occasion",
    options: [],
    availability: "Limited Reserve",
    volumeOptions: [
      { size: "30 ml", price: 195 },
      { size: "50 ml", price: 250 },
      { size: "100 ml", price: 310 },
    ],
    scentAnatomy: {
      story:
        "Atelier Oud is an uncompromising ode to artisanal high perfumery. Aged Southeast Asian agarwood is elevated with threads of red Kashmiri saffron and warm resins.",
      topNotes: "Red Saffron, Incense, Thyme",
      heartNotes: "Artisanal Agarwood (Oud), Rose Petals",
      baseNotes: "Leather Accord, Birch Tar, Smoky Amber",
    },
  },
  {
    id: "rose-absolute",
    name: "Rose Absolute",
    description: "Damask rose balanced with cedar.",
    notes: "Floral / Damask Rose & Cedar",
    price: 205,
    images: ["/images/products/rose-absolute.png"],
    category: "private-reserve",
    scentFamily: "floral",
    occasion: "evening",
    options: [],
    availability: "Available in Atelier",
    volumeOptions: [
      { size: "30 ml", price: 130 },
      { size: "50 ml", price: 170 },
      { size: "100 ml", price: 205 },
    ],
    scentAnatomy: {
      story:
        "Rose Absolute is a sophisticated reinterpretation of classical botanicals. Velvety crimson Damask roses harvested at dawn converge with crisp Atlas cedarwood.",
      topNotes: "Sparkling Pink Peppercorn, Mandarin, Raspberry",
      heartNotes: "Damask Rose Absolute, May Rose, Geranium",
      baseNotes: "Atlas Cedarwood, Guaiac Wood, Clean Amber",
    },
  },
];
